- name: download fluentd
  get_url:
    url: https://storage.googleapis.com/signals-agents/logging/google-fluentd-install.sh
    dest: google-fluentd-install.sh

- name: run startup script
  shell: google-fluentd-install.sh

- name: start fluentd
  service:
    name: google-fluentd
    state: restarted

- name: download cloud SQL proxy
  get_url:
    url: https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
    dest: cloud_sql_proxy

- name: add permission
  file:
    path: /cloud_sql_proxy
    mode: u+x,g+x,o+x

- name: run startup script
  shell: cloud_sql_proxy -instances={{project}}:{{region}}:{{sql_instance}}=tcp:{{port}}
