- name: Clone application from repo
  git:
    repo: {{ app_repo }}
    dest: {{ instalation_path }}
    version: steps

- name: install apt packages
  apt:
    pkg: {{ package_list }}

- name: add user
  user:
    name: {{ app_user }}

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3

- name: upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    virtualenv: "{{ instalation_path }}"/7-gce/env
    virtualenv_python: python3

- name: install dependecies
  pip:
    requirements: "{{ instalation_path }}"/7-gce/requirements.txt
    executable: "{{ instalation_path }}"/7-gce/env/bin/pip3

- name: create config.py
  template:
        src: config.j2
        dest: "{{ instalation_path }}"/7-gce/config.py
        mode: 0666
