- name: Clone application from repo
  git:
    repo: https://github.com/robin88322/getting-started-python.git
    dest: /opt/app
    version: steps

- name: install apt packages
  apt:
    pkg:
    - build-essential
    - supervisor
    - python3-dev
    - python-pip
    - python3-pip
    - python3-venv
    - libffi-dev
    - libssl-dev

- name: add user
  user:
    name: pythonapp

- name: upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    #executable: /opt/app/7-gce/env/bin/pip3
    virtualenv: /opt/app/7-gce/env
    virtualenv_command: venv
    virtualenv_python: python3

- name: install dependecies
  pip:
    requirements: /opt/app/7-gce/requirements.txt
    virtualenv: /opt/app/7-gce/env
    #executable: /opt/app/7-gce/env/bin/pip3

- name: create config.py
  template:
        src: config.j2
        dest: /opt/app/7-gce/config.py
        mode: 0644
